### ISSUE TITLE
Doesn't work in Safari, events not appear, why?

### ISSUE THREAD

**Issue by FelipeVargas86** [benhall14/jquery-calendar#1]

**Comment by benhall14** [comment]
Thanks for the notification.

The Safari browser doesn't like the hyphens used in the event date. If you replace the hyphens with forward slashes, the issue disappears.

For example:

var events = [
    {start: '2017/09/01', end: '2017/09/07', summary: "Example Event", mask: true},
    {start: '2017/09/14', end: '2017/09/20', summary: "Example Event #2", mask: true},
    {start: '2017/10/05', end: '2017/10/15', summary: "Example Event #3", mask: true}
];

I'm going to update the code to reflect this.

Thanks
